fix: add placeholder text to the search input box (resolves #24)
inclusive-design/covid-data-monitor pull request #32
Opened 2021-06-18 18:07 UTC by cindyli

2021-06-18 21:28 UTC, klown requested changes

2021-06-18 21:28 UTC, klown commented on src/html/template.html
> +        <svg role="presentation">
@cindyli When I get a chance, I'll load the page into a browser and see how the a11y tree looks.

Followup:  this looks good.  The label is fixed and the magnifying image isn't in the a11y tree.
👍

2021-06-18 21:28 UTC, klown commented on src/js/autocomplete.js
> +    $("input", container).attr("placeholder", "Search by postal code or city");
Using `@placeholder` as a way of providing a visual label has a11y problems:
* the placeholder text will vanish as soon as the user starts typing in the `<input>`, possibly affecting persons with cognitive issues,
* the placeholder text will not appear as the label for ATs. That might be okay *if* the` <label>` element is still functional even though it isn't visible.

MDN has a critique of `@placeholder`, the section ["Placeholders are not accessible"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#placeholders_are_not_accessible)

Followup a couple hours later:  First, the use of placeholder looks odd when the `<label>` is visible in the larger view.  Users see both the label and the placeholder, and they are identical.  Secondly, the checker is still complaining that the input "should have a visible label" in the mobile, although there is an accessible label.

If it's okay to shrink the warning text and still display it in the mobile view, why not do the same of the search field label?  That is, show it right above the search field.  Is that difficult to do?

2021-06-18 22:21 UTC, cindyli commented on src/js/autocomplete.js
> +    $("input", container).attr("placeholder", "Search by postal code or city");
Thanks for the suggestion, @klown. For now, I make the search label accessible by screen readers on the mobile view. Before, this label was hidden on the mobile so it's not surprising the checker complains that the input "should have a visible label" in the mobile.

Displaying the search label above the search field is not technically difficult. I believe the design removes it from the mobile view is to save space for the map. On a small screen such as iphone 5, the map is fairly small with contents around it.

@uttaraghodke, please let us know what you think. Thanks.

2021-06-21 18:05 UTC, uttaraghodke commented
This looks good to me.

2021-06-21 18:05 UTC, uttaraghodke commented
This looks good to me.

2021-06-21 18:11 UTC, cindyli commented
Reopen as this PR was in progress of the review and merge.

2021-06-22 19:23 UTC, cindyli commented
@klown, @uttaraghodke, the new design of the search area has been implemented. Ready for another review.

2021-06-23 13:56 UTC, klown commented
@cindyli, the label situation is good in the desktop view, but it's missing entirely in the mobile view.  It's not visible and the checker is indicating that there is no label.  See the attached screen shot.  The search field doesn't look like @uttaraghodke's [version](845378).

![MobileView](https://user-images.githubusercontent.com/565007/123108214-393c1d80-d408-11eb-9401-8d0201376807.png)

2021-06-23 13:59 UTC, cindyli commented
> @cindyli, the label situation is good in the desktop view, but it's missing entirely in the mobile view. It's not visible and the checker is indicating that there is no label. See the attached screen shot. The search field doesn't look like @uttaraghodke's [version](845378).

This might because it was using a cached version. Can you clear the browser cache and try again? Thanks.

2021-06-23 14:22 UTC, klown commented
> This might because it was using a cached version. Can you clear the browser cache and try again? Thanks.

Yes, I did that, but to sure, I cleared it again, but I get the same result.

2021-06-23 14:42 UTC, klown commented
> > This might because it was using a cached version. Can you clear the browser cache and try again? Thanks.
> 
> Yes, I did that, but to sure, I cleared it again, but I get the same result.

Based on Element conversation with @cindyli, updating the styles by running `npm run build:scss` fixes the problem.

LGTM -- I'll finish the review.

2021-06-23 14:43 UTC, klown approved these changes

2021-06-23 14:44 UTC, merged